---
version: '3.8'
services:
  nfi:
    ### select targeting image (develop has newer features, more bugs)
    ### plotting branch is for extensive backtesting / machine learning hyperopt
    image: freqtradeorg/freqtrade:stable
    #image: freqtradeorg/freqtrade:develop
    #image: freqtradeorg/freqtrade:develop_plot

    ### Build step - only needed when additional dependencies are needed
    build:
       context: .
       dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: nfi
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./configs:/freqtrade/configs"
      
    ### Use this section to expose api on specified port (localhost only)
    ### Please read the https://www.freqtrade.io/en/latest/rest-api/ documentation
    ### before enabling this.
    #ports:
    #   - "127.0.0.1:8078:8078"


    ### Default command used when running `docker compose up`
    command: >
      trade
      --logfile user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3-okx.sqlite
      --datadir user_data/data/${EXCHANGE:-okx}
      --config user_data/data/okx-usdt-private.json
      --config configs/volumefilter-okx-usdt.json
      --config configs/blacklist-okx.json
      --strategy NostalgiaForInfinityX
  nfi2:
    ### select targeting image (develop has newer features, more bugs)
    ### plotting branch is for extensive backtesting / machine learning hyperopt
    image: freqtradeorg/freqtrade:stable
    #image: freqtradeorg/freqtrade:develop
    #image: freqtradeorg/freqtrade:develop_plot

    ### Build step - only needed when additional dependencies are needed
    build:
       context: .
       dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: nfi2
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./configs:/freqtrade/configs"
      
    ### Use this section to expose api on specified port (localhost only)
    ### Please read the https://www.freqtrade.io/en/latest/rest-api/ documentation
    ### before enabling this.
    #ports:
    #   - "127.0.0.1:8078:8078"


    ### Default command used when running `docker compose up`
    command: >
      trade
      --logfile user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3-nfi2-okx.sqlite
      --datadir user_data/data/${EXCHANGE:-okx}
      --config user_data/data/okx-usdt-private.json
      --config configs/volumefilter-okx-usdt.json
      --config configs/blacklist-okx.json
      --strategy NostalgiaForInfinityX2
  nfi3:
    ### select targeting image (develop has newer features, more bugs)
    ### plotting branch is for extensive backtesting / machine learning hyperopt
    image: freqtradeorg/freqtrade:stable
    #image: freqtradeorg/freqtrade:develop
    #image: freqtradeorg/freqtrade:develop_plot

    ### Build step - only needed when additional dependencies are needed
    build:
       context: .
       dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: nfi3
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./configs:/freqtrade/configs"
      
    ### Use this section to expose api on specified port (localhost only)
    ### Please read the https://www.freqtrade.io/en/latest/rest-api/ documentation
    ### before enabling this.
    #ports:
    #   - "127.0.0.1:8078:8078"


    ### Default command used when running `docker compose up`
    command: >
      trade
      --logfile user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3-nfi3-okx.sqlite
      --datadir user_data/data/${EXCHANGE:-okx}
      --config user_data/data/okx-usdt-private.json
      --config configs/volumefilter-okx-usdt.json
      --config configs/blacklist-okx.json
      --strategy NostalgiaForInfinityX3
  nfi4:
    ### select targeting image (develop has newer features, more bugs)
    ### plotting branch is for extensive backtesting / machine learning hyperopt
    image: freqtradeorg/freqtrade:stable
    #image: freqtradeorg/freqtrade:develop
    #image: freqtradeorg/freqtrade:develop_plot

    ### Build step - only needed when additional dependencies are needed
    build:
       context: .
       dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: nfi4
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./configs:/freqtrade/configs"
      
    ### Use this section to expose api on specified port (localhost only)
    ### Please read the https://www.freqtrade.io/en/latest/rest-api/ documentation
    ### before enabling this.
    #ports:
    #   - "127.0.0.1:8078:8078"


    ### Default command used when running `docker compose up`
    command: >
      trade
      --logfile user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3-nfi4-okx.sqlite
      --datadir user_data/data/${EXCHANGE:-okx}
      --config user_data/data/okx-usdt-private.json
      --config configs/volumefilter-okx-usdt.json
      --config configs/blacklist-okx.json
      --strategy NostalgiaForInfinityX4