FROM freqtradeorg/freqtrade:develop

# Switch user to root if you must install something from apt
# Don't forget to switch the user back below!
USER root

# Dependencies
#RUN pip install pandas-ta

#switching back to normal user
USER ftuser
